[main]
font=JetBrainsMono NFM:size=12
# font-italic=JetBrainsMono NFM Light Italic
# font-bold=JetBrainsMono NFM Medium
# font-bold-italic=Victor Mono Medium Italic
line-height=17.5

[colors]
alpha=0.94

# theme: Dracula
[cursor]
color=282a36 f8f8f2
[colors]
foreground=f8f8f2
background=282a36
regular0=000000  # black
regular1=ff5555  # red
regular2=50fa7b  # green
regular3=f1fa8c  # yellow
regular4=bd93f9  # blue
regular5=ff79c6  # magenta
regular6=8be9fd  # cyan
regular7=bfbfbf  # white
bright0=4d4d4d   # bright black
bright1=ff6e67   # bright red
bright2=5af78e   # bright green
bright3=f4f99d   # bright yellow
bright4=caa9fa   # bright blue
bright5=ff92d0   # bright magenta
bright6=9aedfe   # bright cyan
bright7=e6e6e6   # bright white

# theme: Ayu Mirage
# [cursor]
# color =  ffcc66 665a44
# [colors]
# foreground = cccac2
# background = 242936
# regular0 = 242936 # black
# regular1 = f28779 # red
# regular2 = d5ff80 # green
# regular3 = ffd173 # yellow
# regular4 = 73d0ff # blue
# regular5 = dfbfff # magenta
# regular6 = 5ccfe6 # cyan
# regular7 = cccac2 # white
# bright0 = fcfcfc # bright black
# bright1 = f07171 # bright red
# bright2 = 86b300 # bright gree
# bright3 = f2ae49 # bright yellow
# bright4 = 399ee6 # bright blue
# bright5 = a37acc # bright magenta
# bright6 = 55b4d4 # bright cyan
# bright7 = 5c6166 # bright white
